### ISSUE TITLE
Consider dropping the udev rule file using PIP

### ISSUE THREAD

**Issue by davidstrauss** [eltuxusb/eltuxusb#17]
We can technically drop the udev rules file using PIP. It's the same location on Fedora and Ubuntu, so it should be broadly distro-compatible. I'm not sure how clean it is, though, especially for folks who install this using PIP with virtualenv.

**Comment by xens** [comment]
Interesting, I thought of creating the rule directly form the installer, is it something else ?

**Comment by davidstrauss** [comment]
There's a semantic way to specify extra files that get dropped with a package. See the "data files" entry from this other project I maintain: https://github.com/davidstrauss/perfbucket/blob/master/setup.py

**Comment by xens** [comment]
Ok nice I did some tests locally and seems to be pretty slick.

I still have a problem on recent ubuntu releases, the following rule won't work anymore:
SUBSYSTEM=="usb", ATTR{idVendor}=="10c4", ATTR{idProduct}=="0002", MODE:="0666"

I have to assign it to a GROUP and add my user to this group:
SUBSYSTEM=="usb", ATTR{idVendor}=="10c4", ATTR{idProduct}=="0002", MODE:="0666", GROUP:="usbusers"

I don't know if it's the same in Fedora, but will it be possible to do those operations with PIP or with a post-install script?

**Comment by xens** [comment]
Ok I added the file, tested and work under ubuntu. The group problem may be solved by hand by creating a group. I updated the README.
