### ISSUE TITLE
PIP installer doesn't work anymore

### ISSUE THREAD

**Issue by xens** [eltuxusb/eltuxusb#19]
For testing purpose I tried to install eltuxusb with the command

sudo pip install git+http://github.com/eltuxusb/eltuxusb.git#egg=eltuxusb

before that I removed the directory:
/usr/local/lib/python2.7/dist-packages/

here's the output:
xens@xen-laptop:~/Bureau/temp_test$ eltuxusb -d
Traceback (most recent call last):
  File "/usr/local/bin/eltuxusb", line 14, in <module>
    from eltuxusb.el_ui import eltuxusb
ImportError: No module named eltuxusb.el_ui

I think it's since the UI and main program separation ?
If I install manually it works (python setup.py install)

**Comment by davidstrauss** [comment]
Any import lines in the executable need to work whether they're in the same directory or the rest of eltuxusb is installed (probably with PIP) as a module.

**Comment by xens** [comment]
Ok sorry for the noise, it was my fault, the installer is working. I had too much mess in my setup, now when I test it from scratch I completely remove the files before... sudo pip uninstall eltuxusb
