### ISSUE TITLE
plot not rightly rendered with 10s recording steps

### ISSUE THREAD

**Issue by xens** [eltuxusb/eltuxusb#21]
We noticed that the graphing software is not working correctly, although we had used 10s logging the data is being graphed in 1 minute slots, I have attached the file

Example file:
EasyLog USB,Time,Celsius(°C),Serial Number
1,07/06/2012 09:49:00,28.5,10023388
2,07/06/2012 09:49:10,29.0
3,07/06/2012 09:49:20,28.5
4,07/06/2012 09:49:30,28.0
5,07/06/2012 09:49:40,27.5
6,07/06/2012 09:49:50,27.0
7,07/06/2012 09:50:00,26.5
8,07/06/2012 09:50:10,26.5
9,07/06/2012 09:50:20,26.0
10,07/06/2012 09:50:30,26.0
11,07/06/2012 09:50:40,25.5
12,07/06/2012 09:50:50,25.5
13,07/06/2012 09:51:00,25.0
14,07/06/2012 09:51:10,25.5
15,07/06/2012 09:51:20,26.0
16,07/06/2012 09:51:30,26.0
17,07/06/2012 09:51:40,26.5
18,07/06/2012 09:51:50,27.0
19,07/06/2012 09:52:00,27.5
20,07/06/2012 09:52:10,27.5
21,07/06/2012 09:52:20,28.0
22,07/06/2012 09:52:30,28.0
23,07/06/2012 09:52:40,28.0
24,07/06/2012 09:52:50,28.5
25,07/06/2012 09:53:00,28.5
26,07/06/2012 09:53:10,28.0
27,07/06/2012 09:53:20,27.5
28,07/06/2012 09:53:30,27.5
29,07/06/2012 09:53:40,28.0
30,07/06/2012 09:53:50,28.5
31,07/06/2012 09:54:00,28.5
32,07/06/2012 09:54:10,28.5
33,07/06/2012 09:54:20,29.0
34,07/06/2012 09:54:30,29.0
35,07/06/2012 09:54:40,29.0
36,07/06/2012 09:54:50,29.0
37,07/06/2012 09:55:00,29.0
38,07/06/2012 09:55:10,29.0
39,07/06/2012 09:55:20,29.0
40,07/06/2012 09:55:30,29.0
41,07/06/2012 09:55:40,29.5
42,07/06/2012 09:55:50,29.5
43,07/06/2012 09:56:00,29.5
44,07/06/2012 09:56:10,29.5
45,07/06/2012 09:56:20,29.5

Ian from Lascar Electronics

**Comment by scandyna** [comment]
Hi,
Taking a look in el_plot.py, function render_plot(), it seems that matplotit is based on gnuplot (matlab/octave like syntax).
Possible solution could be here: http://linuxgazette.net/126/peterson.html  ?
I try'd this with gnuplot:
Modify example file:
07/06/2012-09:49:00 28.5
07/06/2012-09:49:10 29.0
07/06/2012-09:49:20 28.5
07/06/2012-09:49:30 28.0
07/06/2012-09:49:40 27.5
07/06/2012-09:49:50 27.0
07/06/2012-09:50:00 26.5
07/06/2012-09:50:10 26.5
07/06/2012-09:50:20 26.0
07/06/2012-09:50:30 26.0
07/06/2012-09:50:40 25.5
07/06/2012-09:50:50 25.5
07/06/2012-09:51:00 25.0
07/06/2012-09:51:10 25.5
07/06/2012-09:51:20 26.0
07/06/2012-09:51:30 26.0
07/06/2012-09:51:40 26.5
07/06/2012-09:51:50 27.0
07/06/2012-09:52:00 27.5
07/06/2012-09:52:10 27.5
07/06/2012-09:52:20 28.0
07/06/2012-09:52:30 28.0
07/06/2012-09:52:40 28.0
07/06/2012-09:52:50 28.5
07/06/2012-09:53:00 28.5
07/06/2012-09:53:10 28.0
07/06/2012-09:53:20 27.5
07/06/2012-09:53:30 27.5
07/06/2012-09:53:40 28.0
07/06/2012-09:53:50 28.5
07/06/2012-09:54:00 28.5
07/06/2012-09:54:10 28.5
07/06/2012-09:54:20 29.0
07/06/2012-09:54:30 29.0
07/06/2012-09:54:40 29.0
07/06/2012-09:54:50 29.0
07/06/2012-09:55:00 29.0
07/06/2012-09:55:10 29.0
07/06/2012-09:55:20 29.0
07/06/2012-09:55:30 29.0
07/06/2012-09:55:40 29.5
07/06/2012-09:55:50 29.5
07/06/2012-09:56:00 29.5
07/06/2012-09:56:10 29.5
07/06/2012-09:56:20 29.5
Run gnuplot, and type these commands:
set xdata time
set timefmt "%d/%m/%Y-%H:%M:%S"
plot "./test_eltuxusb.dat" using 1:2 index 0 with lines

The result is something not to bad.

To have a better result, you could specify the ranges:
set xdata time
set timefmt "%d/%m/%Y-%H:%M:%S"
set xrange ["07/06/2012 09:49:00" : "07/06/2012 09:56:20"]
set yrange [-20:40]
plot "./test_eltuxusb.dat" using 1:2 index 0 with lines

But, could be a little "hack" to extract the range from data file ?

**Comment by xens** [comment]
Hi Scandyna thanks for your feedback !

I never set the "X" range like you did in your example. Instead I use the full date string ex: "07/06/2012-09:52:00" formated as date for each entry. The problem in my case is that I forgot to add the "seconds" to the date entries. It's now corrected.
By the way the plotting side of the program is really messy and the generated graphs are not very well shaped so a lot of work will be required soon here :>

I close this issue

Romain
