### ISSUE TITLE
migrate from gtk2 to gtk3

### ISSUE THREAD

**Issue by xens** [eltuxusb/eltuxusb#22]
I'm not sure how it will affect gnome 2 users but all the tools I use (glade builder, ...) are now generating gtk3 files so I'll move the eltuxusb this way.

**Comment by davidstrauss** [comment]
I don't have any boxes that still run GTK3. I recommend just going GTK3. It's not like upgrading to it costs money.

**Comment by xens** [comment]
Ok we're now using GTK3 libraries, I tested as much as I could everything seems to work here, I close the issue
